var base = 0;
//数学chapter1常量定义
var MATH_BIXIU1_CHAPTER1_TUR1_1 = base++;
var MATH_BIXIU1_CHAPTER1_TUR1_2 = base++;
var MATH_BIXIU1_CHAPTER1_TUR1_3 = base++;
var MATH_BIXIU1_CHAPTER1_TUR2_1 = base++;
var MATH_BIXIU1_CHAPTER1_TUR2_2 = base++;
var MATH_BIXIU1_CHAPTER1_TUR2_3 = base++;
var MATH_BIXIU1_CHAPTER1_TUR2_4 = base++;

//数学chapter2常量定义
var MATH_BIXIU1_CHAPTER2_TUR1_1 = base++;
var MATH_BIXIU1_CHAPTER2_TUR1_2 = base++;
var MATH_BIXIU1_CHAPTER2_TUR2_1 = base++;
var MATH_BIXIU1_CHAPTER2_TUR2_2 = base++;
var MATH_BIXIU1_CHAPTER2_TUR2_3 = base++;
var MATH_BIXIU1_CHAPTER2_TUR2_4 = base++;
var MATH_BIXIU1_CHAPTER2_TUR2_5 = base++;

//数学简史常量定义
var MATH_HISTORY_CHAPTER1_TUR1_1 = base++;
var MATH_HISTORY_CHAPTER1_TUR1_2 = base++;
var MATH_HISTORY_CHAPTER1_TUR1_3 = base++;

var MATH_HISTORY_CHAPTER2_TUR1_1 = base++;
var MATH_HISTORY_CHAPTER2_TUR1_2 = base++;
var MATH_HISTORY_CHAPTER2_TUR1_3 = base++;
var MATH_HISTORY_CHAPTER2_TUR1_4 = base++;
var MATH_HISTORY_CHAPTER2_TUR1_5 = base++;
var MATH_HISTORY_CHAPTER2_TUR1_6 = base++;
var MATH_HISTORY_CHAPTER2_TUR1_7 = base++;
var MATH_HISTORY_CHAPTER2_TUR1_8 = base++;

var MATH_HISTORY_CHAPTER3_TUR1_1 = base++;
var MATH_HISTORY_CHAPTER3_TUR1_2 = base++;
var MATH_HISTORY_CHAPTER3_TUR1_3 = base++;
var MATH_HISTORY_CHAPTER3_TUR1_4 = base++;
var MATH_HISTORY_CHAPTER3_TUR1_5 = base++;
var MATH_HISTORY_CHAPTER3_TUR1_6 = base++;
var MATH_HISTORY_CHAPTER3_TUR1_7 = base++;

var MATH_HISTORY_CHAPTER4_TUR1_1 = base++;
var MATH_HISTORY_CHAPTER4_TUR1_2 = base++;
var MATH_HISTORY_CHAPTER4_TUR1_3 = base++;
var MATH_HISTORY_CHAPTER4_TUR1_4 = base++;
var MATH_HISTORY_CHAPTER4_TUR1_5 = base++;
var MATH_HISTORY_CHAPTER4_TUR1_6 = base++;

var MATH_HISTORY_CHAPTER5_TUR1_1 = base++;
var MATH_HISTORY_CHAPTER5_TUR1_2 = base++;
var MATH_HISTORY_CHAPTER5_TUR1_3 = base++;
var MATH_HISTORY_CHAPTER5_TUR1_4 = base++;
var MATH_HISTORY_CHAPTER5_TUR1_5 = base++;

var MATH_HISTORY_CHAPTER6_TUR1_1 = base++;
var MATH_HISTORY_CHAPTER6_TUR1_2 = base++;
var MATH_HISTORY_CHAPTER6_TUR1_3 = base++;
var MATH_HISTORY_CHAPTER6_TUR1_4 = base++;
var MATH_HISTORY_CHAPTER6_TUR1_5 = base++;